apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-headless'
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: etcd
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: etcd
  ports:
    - name: client
      port: 2379
      targetPort: client
      nodePort: {{ required "nodePort is required" .Values.nodePort }}
