apiVersion: operator.kcp.io/v1alpha1
kind: RootShard
metadata:
  name: root
spec:
  external:
    hostname: front-proxy-front-proxy.kcp.svc.cluster.local
    port: 6443
  certificates:
    issuerRef:
      group: cert-manager.io
      kind: Issuer
      name: selfsigned
  cache:
    embedded:
      enabled: true
  etcd:
    endpoints:
      - http://etcd-root.kcp.svc.cluster.local:2379
  image:
    tag: main@sha256:d62bcc93a1d2a09d7ce40dea1a9f100bc0e376cd9cd9b6d3ba676c32329d60ce
  replicas: 1
  extraArgs:
    - --feature-gates=LogicalClusterMigration=true
  proxy:
    image:
      tag: main@sha256:d62bcc93a1d2a09d7ce40dea1a9f100bc0e376cd9cd9b6d3ba676c32329d60ce
    replicas: 1
