kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5
    # NodePorts: front-proxy and one etcd per shard, see demo/kcp and Makefile.
    extraPortMappings:
      - containerPort: 30443
        hostPort: 6443
        listenAddress: 127.0.0.1
      - containerPort: 30379
        hostPort: 23790
        listenAddress: 127.0.0.1
      - containerPort: 30380
        hostPort: 23791
        listenAddress: 127.0.0.1
      - containerPort: 30381
        hostPort: 23792
        listenAddress: 127.0.0.1
